server:
  host: 127.0.0.1
  port: 9090

Redis:
  host: 106.52.78.230
  port: 6379

Mysql:
  host: 106.52.78.230
  port: 3306
  password: "0503"
  dbname: chat
  user: root

Consul:
  host: 106.52.78.230
  port: 8500

RabbitMQ:
  host: 106.52.78.230
  port: 5672
  user: username
  password: password


Etcd:
  host: 106.52.78.230
  port: 2379
  service: /services/im
  user:
  password: